version: '3'

services:
  ui:
    image: jmcsquiggle/capstone-ui
    ports:
    - "80:8080"
    links:
    - api
    networks:
    - backend
  api:
    image: jmcsquiggle/capstone-api
    ports:
    - "4200:4200"
    networks:
    - backend
networks:
  backend:
    driver: "bridge"